### ISSUE TITLE
State Shape

### ISSUE THREAD

**Issue by linakherchi** [colineckert/everbrain#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
Thanks, Colin ! 

You do not need to have notebookIds and noteIds arrays in your state shape, as you already are saving their respective foreign keys (authorId & notebookId).

**Comment by colineckert** [comment]
Got it, thanks, Lina! Issue addressed. 

I wasn't sure if I needed to store them in arrays since I believe you said the browser doesn't handle ordering. I was thinking I'll need to organize and present notes by `updated_at` in the notebooks and notebooks by `created_at`, but I'm sure there's a better solution.

**Comment by linakherchi** [comment]
Thanks, Colin ! 

Ordering notes by `updated_at` and notebooks by `created_at` is actually a good idea.

**Comment by colineckert** [comment]
OK great! I reverted my sample state back to the version that stored the Id arrays. Let me know if that works!

**Comment by linakherchi** [comment]
That looks very good to me ! 

This is a note to myself: 
  + NotebookIds will need to be ordered in your controller by `created_at` column 
  + NoteIds will need to be ordered in your controller by `updated_at` column
