### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [colineckert/everbrain#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Thanks, Colin ! 

No need to have nested routes in your note_tags. 

Do you even need to have note_tags routes ? I believe that as soon as you create a tag, it will need to be associated to a note, unless Evernote allows you to create tags without these necessarily being associated with a note.

Let me know !

**Comment by colineckert** [comment]
Sure thing, Lina! 

Yeah, so I was playing with tags before making the routes and you can in fact create a new tag without attaching it to a note, which is what made me think I needed separate routes to create/delete a tag and for adding/removing them to/from notes (which I thought needed to be nested so I could get the note_id from params). 

Is there a better/simpler solution you recommend? Perhaps I should just build it so tags must be attached to a note when created?

**Comment by linakherchi** [comment]
Thanks, Colin ! 

It will definitely be simpler to immediately associate a note to a tag when a tag is created but if you want to give the user the ability to create a tag and then decide to which note it needs to be associated, a route such as `/api/note_tags` will be enough.
In fact, you will be able to send that tagId and noteId to your backend without necessarily having those available in your backend routes as wild cards.

Happy to chat if you want me to clarify it further !

**Comment by colineckert** [comment]
Thanks, Lina! Yeah, I can just start by just immediately associating a note to a tag when a tag is created, since that would be a lot simpler, and build the functionality later to allow for unassociated tags.

It would be great to chat about this to make sure I understand! No rush though, in the meantime I can remove those backend routes. Thanks!

**Comment by colineckert** [comment]
Hi Lina, is this clear to start today?
