### ISSUE TITLE
User auth MVP

### ISSUE THREAD

**Issue by linakherchi** [colineckert/everbrain#7]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
Thanks, Colin ! 

1. When a user is signed in and tries to go to /login or /sign, it is better to redirect that user to /home instead of /, which is a route that does not seem to be related to a component;
2. Please complete the checklist based on the unchecked boxes above;

Let me know if you have questions.

Lina

**Comment by colineckert** [comment]
Thanks, Lina! This all makes sense and I think I've addressed the open items. 

I do have `"/"` tied to my `Home` component, and am now using a switch in my App.jsx routes to direct to a new 404 component. 

```jsx
    <Switch>
      <AuthRoute path="/login" component={LoginFormContainer} />
      <AuthRoute path="/signup" component={SignupFormContainer} />

      <ProtectedRoute path="/notes" component={Main} />

      <Route exact path="/" component={Home} />
      <Route component={NotFound} />
    </Switch>
```

I also tested hitting enter on my login form and checked the next state, and the form data credentails were reflected in my next state. 

Let me know if anything is still missing/incorrect. Thanks!
