### ISSUE TITLE
Notebooks MVP

### ISSUE THREAD

**Issue by colineckert** [colineckert/everbrain#8]
Notebooks CRUD is ready for your review. Thanks!

**Comment by linakherchi** [comment]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
Thanks, Colin ! 

Make sure to render errors when there is an empty field on Notebook creation & update.

**Comment by colineckert** [comment]
Thanks, Lina! I've added this functionality so that the create and update modals will render an error if submitted with blank inputs. I've pushed to heroku and it's ready for you to test. Thanks!
